<?php

/**
 * @file
 * This file utilizes the presave hook to replace local media URLs to Filerobot URLs
 */

/**
 * Implements hook_ENTITY_TYPE_presave
 */
function filerobot_file_presave(\Drupal\Core\Entity\EntityInterface $entity) 
{
	kint($entity);//@Todo: This is yet unfinished
}

/**
 * Implements hook_theme().
 */
function filerobot_theme($existing, $type, $theme, $path) 
{
    return [
        'filerobot_template' => [
            'variables' => [
                'dummy_placeholder' => NULL,
            ],
        ],
        'fmaw_template' => [
            'variables' => [
                'token_var' => NULL,
                'sectemp_var' => NULL,
                'folder_var' => NULL,
            ],
        ],
        'filerobot_log_template' => [
            'variables' => [
                'log_data' => NULL,
            ],
        ],
    ];
}
