<?php

/**
 * @file
 * This file utilizes the presave hook to replace local media URLs to Filerobot URLs
 */

/**
 * Implements hook_ENTITY_TYPE_presave
 */
function filerobot_file_presave(\Drupal\file\FileInterface $file)
{
    //@Todo: Upload to Filerobot platform
    // https://scaleflexhq.atlassian.net/wiki/spaces/~56460122/pages/124813313/Filerobot+Platform#The-APIs-(Detail)

    //@Todo: Get response info to construct Filerobot URL

    // https://api.drupal.org/api/drupal/core%21modules%21file%21src%21FileInterface.php/interface/FileInterface/10
    $file->setFileUri('https://www.sample.li/boat.jpg'); //@Todo: Gotta finish this the proper way
    // Potential problem: https://drupal.slack.com/archives/C1BB308HH/p1678725331795619

    //@Todo: Save an entry to filerobot_sync_logs table
}

/**
 * Implements hook_theme().
 */
function filerobot_theme($existing, $type, $theme, $path)
{
    return [
        'filerobot_template' => [
            'variables' => [
                'dummy_placeholder' => NULL,
            ],
        ],
        'fmaw_template' => [
            'variables' => [
                'token' => NULL,
                'SEC' => NULL,
                'uploadDirectory' => NULL,
            ],
        ],
        'filerobot_log_template' => [
            'variables' => [
                'log_data' => NULL,
            ],
        ],
    ];
}

/**
 * Implements hook_form_alter().
 */
function filerobot_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'media_library_add_form') {
    $form['actions']['submit']['#submit'][] = 'filerobot_media_library_add_form_submit';
  }
}

function filerobot_media_library_add_form_submit($form, &$form_state) {
  // Your custom code to handle the file upload goes here.
  echo 'override';
}
