<?php

/**
 * @file
 * This file utilizes the presave hook to replace local media URLs to Filerobot URLs
 */

/**
 * Implements hook_ENTITY_TYPE_presave
 */
function filerobot_file_presave(\Drupal\file\FileInterface $file)
{
    //@Todo: Upload to Filerobot platform
    // https://scaleflexhq.atlassian.net/wiki/spaces/~56460122/pages/124813313/Filerobot+Platform#The-APIs-(Detail)

    //@Todo: Get response info to construct Filerobot URL

    // https://api.drupal.org/api/drupal/core%21modules%21file%21src%21FileInterface.php/interface/FileInterface/10
    $file->setFileUri('https://www.sample.li/boat.jpg'); //@Todo: Gotta finish this the proper way
    // Potential problem: https://drupal.slack.com/archives/C1BB308HH/p1678725331795619

    //@Todo: Save an entry to filerobot_sync_logs table
}

/**
 * Implements hook_page_attachments().
 */
function filerobot_page_attachments(array &$attachments) {
  $config = \Drupal::config('filerobot.admin_settings');
  $activation = $config->get('activation');
  $token = $config->get('token');
  if ($activation && $token != '') {
    $attachments['#attached']['library'][] = 'filerobot/fr-library';

    $config_data = [
      'token' => $config->get('token_or_cname'),
      'activation' => $config->get('activation'),
      'CNAME' => $config->get('CNAME'),
      'SEC' => $config->get('SEC'),
      'uploadDirectory' => $config->get('uploadDirectory')
    ];

    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#value' => 'const frSettings = ' . json_encode($config_data) . ';'
      ],
      'frSettings',
    ];
    $attachments['#attached']['library'][] = 'filerobot/filerobot-js';
  }
}
